{% set name = "somacore" %}
{% set version = "1.0.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# Cheat sheet:
# wget 'https://pypi.io/packages/source/s/somacore/somacore-i.j.k.tar.gz'
# shasum -a 256 somacore-i.j.k.tar.gz
source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/somacore-{{ version }}.tar.gz
  sha256: f67e5a9f65d16a3996d7c03aa679cc7529cc0bcc37cf0498dbcbe726971237cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.9
    - anndata
    - attrs >=22.1
    - numba
    - numpy >=1.21
    - pandas
    - pyarrow
    - pyarrow-hotfix
    - scipy
    - shapely
    - typing-extensions >=4.1 # For LiteralString
# See also https://github.com/single-cell-data/SOMA/blob/VERSION-GOES-HERE/pyproject.toml

test:
  imports:
    - somacore
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python-language API specification and base utilities for implementation of the SOMA system.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Shelnutt2
    - nguyenv
    - thetorpedodog
    - johnkerl
