{% set name = "somacore" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/somacore-{{ version }}.tar.gz
  sha256: d5a741c9db3ee7dd6408b425d06bea7a77b17c002956bb8426b01e1905b654a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.dev0
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.7
    - anndata
    - attrs >=22.1
    - numba
    - numpy >=1.21
    - pandas
    - pyarrow
    - scipy
    - typing-extensions >=4.1 # For LiteralString
# See also https://github.com/single-cell-data/SOMA/blob/VERSION-GOES-HERE/pyproject.toml

test:
  imports:
    - somacore
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python-language API specification and base utilities for implementation of the SOMA system.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Shelnutt2
    - nguyenv
    - thetorpedodog
